## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [10]:
#the first try
np.ones(10) * 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [13]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [14]:
x[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [28]:
[x for x,y in enumerate([1,2,0,0,4,0]) if y != 0]

[0, 1, 4]

In [32]:
x =  [1,2,0,0,4,0]
np.array([i for i in range(len(x)) if x[i] != 0])

array([0, 1, 4])

In [31]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [34]:
np.random.random((3,3,3))

array([[[0.14872022, 0.85901006, 0.10826224],
        [0.26745208, 0.79093532, 0.54732255],
        [0.1788135 , 0.9071036 , 0.10526501]],

       [[0.32471897, 0.58165944, 0.9399227 ],
        [0.50465966, 0.38631509, 0.62145721],
        [0.09651995, 0.84708614, 0.63503758]],

       [[0.26340998, 0.42774899, 0.02690013],
        [0.1706352 , 0.92386159, 0.51380394],
        [0.27243385, 0.11875546, 0.50316289]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [35]:
np.mean(np.random.random(30))

0.4767931584906376

Перемножить матрицы 5x3 и 3x2

In [39]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [43]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Заменить максимальный элемент на ноль

In [49]:
x = np.array([1,2,3,5,4])
x[x.argmax()] = 0

Преобразовать массив из float в int

In [ ]:
z = np.arange(10, dtype = int32)
z = np.astype(np.float32, copy = False)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [65]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.59230179 0.28955967 0.22903663 0.5022906  0.67890767
  0.11329773 0.62560717 0.5843761  0.83974582]
 [0.59230179 0.         0.32168304 0.6167004  0.39290112 0.56775734
  0.52205082 0.6185694  0.65180427 0.25168498]
 [0.28955967 0.32168304 0.         0.39983917 0.27312671 0.62847705
  0.25731646 0.62287631 0.61672617 0.57334706]
 [0.22903663 0.6167004  0.39983917 0.         0.66379104 0.50145856
  0.15602816 0.42707475 0.37307809 0.8367541 ]
 [0.5022906  0.39290112 0.27312671 0.66379104 0.         0.86926078
  0.51159503 0.88009947 0.8822092  0.59893674]
 [0.67890767 0.56775734 0.62847705 0.50145856 0.86926078 0.
  0.56618618 0.10989503 0.18733762 0.64399561]
 [0.11329773 0.52205082 0.25731646 0.15602816 0.51159503 0.56618618
  0.         0.51625029 0.47950489 0.76156892]
 [0.62560717 0.6185694  0.62287631 0.42707475 0.88009947 0.10989503
  0.51625029 0.         0.07817009 0.72659564]
 [0.5843761  0.65180427 0.61672617 0.37307809 0.8822092  0.18733762
  0.47950489 0.07817

Случайно расположить p элементов в 2D массив

In [64]:
n = 5
p = 3
X = np.zeros((n,n))
np.put(X, np.random.choice(range(n*n), p, replace=False), 1)
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [68]:
x = np.array([1,2,3,4,5])
cnt = 3
y = np.zeros(len(x) + (len(x)-1)*(cnt))
y[::cnt+1] = x
y

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [69]:
x = np.random.randint(0,5,10)
print(np.bincount(x).argmax())

4


Найти n наибольших значений в массиве

In [70]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5

x[np.argpartition(-x,n)[:n]]

array([9997, 9996, 9998, 9999, 9995])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

note from docs:
low_memory : boolean, default True

Internally process the file in chunks, resulting in lower memory use while parsing, but possibly mixed type inference. To ensure no mixed types either set False, or specify the type with the dtype parameter. Note that the entire file is read into a single DataFrame regardless, use the chunksize or iterator parameter to return the data in chunks. (Only valid with C parser)

In [2]:
import pandas as pd
food = pd.read_csv("food.tsv", sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [3]:
food.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [6]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB


In [9]:
len(food)

356027

Сколько столбцов в наборе данных?

In [10]:
len(food.columns)

163

Напечатайте все названия столбцов

In [15]:
for y,x in enumerate(food.columns, start = 1):
    print(y,x)

1 code
2 url
3 creator
4 created_t
5 created_datetime
6 last_modified_t
7 last_modified_datetime
8 product_name
9 generic_name
10 quantity
11 packaging
12 packaging_tags
13 brands
14 brands_tags
15 categories
16 categories_tags
17 categories_en
18 origins
19 origins_tags
20 manufacturing_places
21 manufacturing_places_tags
22 labels
23 labels_tags
24 labels_en
25 emb_codes
26 emb_codes_tags
27 first_packaging_code_geo
28 cities
29 cities_tags
30 purchase_places
31 stores
32 countries
33 countries_tags
34 countries_en
35 ingredients_text
36 allergens
37 allergens_en
38 traces
39 traces_tags
40 traces_en
41 serving_size
42 no_nutriments
43 additives_n
44 additives
45 additives_tags
46 additives_en
47 ingredients_from_palm_oil_n
48 ingredients_from_palm_oil
49 ingredients_from_palm_oil_tags
50 ingredients_that_may_be_from_palm_oil_n
51 ingredients_that_may_be_from_palm_oil
52 ingredients_that_may_be_from_palm_oil_tags
53 nutrition_grade_uk
54 nutrition_grade_fr
55 pnns_groups_1
56 pnns_gr

Какое название у 105 столбца?

In [11]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [20]:
food['-glucose_100g'].dtype

dtype('float64')

Как проиндексирован набор данных?

In [21]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [27]:
food['product_name'].iloc[18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [3]:
import pandas as pd
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [31]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB


Как много продуктов стоят более чем $10.00?

In [42]:
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)
len(chipo[chipo['item_price'] > 10.00])

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [52]:
for index, row in chipo[['item_name','item_price']].iterrows():
    print("The name of the item is {} prece is {}".format(row['item_name'], row['item_price']))

The name of the item is Chips and Fresh Tomato Salsa prece is 2.39
The name of the item is Izze prece is 3.39
The name of the item is Nantucket Nectar prece is 3.39
The name of the item is Chips and Tomatillo-Green Chili Salsa prece is 2.39
The name of the item is Chicken Bowl prece is 16.98
The name of the item is Chicken Bowl prece is 10.98
The name of the item is Side of Chips prece is 1.69
The name of the item is Steak Burrito prece is 11.75
The name of the item is Steak Soft Tacos prece is 9.25
The name of the item is Steak Burrito prece is 9.25
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chicken Crispy Tacos prece is 8.75
The name of the item is Chicken Soft Tacos prece is 8.75
The name of the item is Chicken Bowl prece is 11.25
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chips and Tomatillo-Green Chili Salsa prece is 2.39
The name of the item is Chicken Burrito prece is 8.49
The name of the item is Chick

The name of the item is Chicken Bowl prece is 8.75
The name of the item is Chips prece is 2.15
The name of the item is Canned Soft Drink prece is 1.25
The name of the item is Carnitas Burrito prece is 11.48
The name of the item is Chicken Burrito prece is 10.98
The name of the item is Chicken Salad prece is 10.98
The name of the item is Chicken Bowl prece is 8.49
The name of the item is Chips and Roasted Chili Corn Salsa prece is 2.95
The name of the item is Barbacoa Bowl prece is 9.25
The name of the item is Steak Burrito prece is 9.25
The name of the item is Steak Burrito prece is 11.75
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Steak Burrito prece is 11.48
The name of the item is Chicken Bowl prece is 11.25
The name of the item is Veggie Burrito prece is 8.75
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Side of Chips prece is 1.69
The name of the item is Steak Bowl prece is 8.99
The name of the item is Chick

The name of the item is Chips prece is 2.15
The name of the item is Canned Soft Drink prece is 1.25
The name of the item is Steak Burrito prece is 8.99
The name of the item is Canned Soda prece is 1.09
The name of the item is Chicken Bowl prece is 8.75
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chicken Bowl prece is 26.25
The name of the item is Chicken Bowl prece is 8.75
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Steak Burrito prece is 11.75
The name of the item is Chips and Tomatillo Green Chili Salsa prece is 2.95
The name of the item is Chicken Bowl prece is 8.75
The name of the item is Chicken Burrito prece is 8.75
The name of the item is Steak Burrito prece is 11.75
The name of the item is Chicken Burrito prece is 8.75
The name of the item is Chicken Bowl prece is 11.25
The name of the item is Chicken Salad Bowl prece is 11.25
The name of the item is Chicken Bowl prece is 11.25
The name of the item is C

The name of the item is Chicken Burrito prece is 11.25
The name of the item is Chicken Burrito prece is 11.25
The name of the item is Chicken Bowl prece is 8.75
The name of the item is Chips prece is 2.15
The name of the item is Bottled Water prece is 1.5
The name of the item is Barbacoa Burrito prece is 9.25
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chicken Burrito prece is 10.98
The name of the item is Steak Burrito prece is 8.99
The name of the item is Canned Soda prece is 2.18
The name of the item is Chicken Burrito prece is 8.75
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Canned Soft Drink prece is 1.25
The name of the item is Steak Soft Tacos prece is 8.99
The name of the item is Chips and Roasted Chili-Corn Salsa prece is 2.39
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chicken Burrito prece is 8.75
The name of the item is Chicken Burrito prece is 10.98
The name of

The name of the item is Chicken Burrito prece is 8.75
The name of the item is Chips prece is 2.15
The name of the item is Chicken Burrito prece is 8.75
The name of the item is Canned Soft Drink prece is 3.75
The name of the item is Steak Burrito prece is 9.25
The name of the item is Chicken Burrito prece is 11.25
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is 6 Pack Soft Drink prece is 6.49
The name of the item is Chicken Bowl prece is 16.98
The name of the item is Steak Burrito prece is 18.5
The name of the item is Canned Soft Drink prece is 2.5
The name of the item is Chips and Tomatillo Red Chili Salsa prece is 2.95
The name of the item is Chips and Guacamole prece is 3.99
The name of the item is Chicken Burrito prece is 8.49
The name of the item is Chicken Burrito prece is 8.19
The name of the item is Steak Burrito prece is 11.08
The name of the item is 6 Pack Soft Drink prece is 6.49
The name of the item is Steak Bowl prece is 11.75
The name of t

The name of the item is Chicken Burrito prece is 8.75
The name of the item is Chips prece is 4.3
The name of the item is Chicken Bowl prece is 8.75
The name of the item is Canned Soft Drink prece is 1.25
The name of the item is Chips and Tomatillo Green Chili Salsa prece is 2.95
The name of the item is Steak Soft Tacos prece is 9.25
The name of the item is Chips and Tomatillo Red Chili Salsa prece is 2.95
The name of the item is Chips and Guacamole prece is 4.45
The name of the item is Chicken Bowl prece is 11.25
The name of the item is Veggie Burrito prece is 11.25
The name of the item is Barbacoa Bowl prece is 9.25
The name of the item is Carnitas Soft Tacos prece is 9.25
The name of the item is Bottled Water prece is 4.5
The name of the item is Steak Burrito prece is 11.75
The name of the item is Canned Soft Drink prece is 1.25
The name of the item is Barbacoa Bowl prece is 11.75
The name of the item is Carnitas Burrito prece is 11.75
The name of the item is Canned Soft Drink prece 

Отсортировать по имени предмета

In [55]:
chipo.sort_values(by='item_name').head()

order_id  quantity          item_name choice_description  item_price
3389      1360         2  6 Pack Soft Drink        [Diet Coke]       12.98
341        148         1  6 Pack Soft Drink        [Diet Coke]        6.49
1849       749         1  6 Pack Soft Drink             [Coke]        6.49
1860       754         1  6 Pack Soft Drink        [Diet Coke]        6.49
2713      1076         1  6 Pack Soft Drink             [Coke]        6.49

Сколько было заказано самого дорогого предмета?

In [57]:
chipo.iloc[chipo['item_price'].idxmax()]['quantity']

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [63]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [66]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20